---
  - hosts: vmware
    remote_user: ansible
    become: yes
    tasks:
      - name: Create a virtual machine on given ESXi hostname
        vmware_guest:
          hostname: 192.168.6.130
          username: root
          password: P@ssword
          validate_certs: no
          folder: /
          name: vm-dorneles-pb
          state: poweredon
          guest_id: ubuntu64Guest
#          esxi_hostname: 10.2.11.45
          disk:
            - size_gb: 30
              type: thin
              datastore: Datastore-Frdorneles
          hardware:
            memory_mb: 2048
            num_cpus: 2
            scsi: paravirtual
          cdrom:
            - controller_number: 0
              unit_number: 0
              state: present
              type: iso
              iso_path: "[Datastore-Frdorneles] ubuntu-20.04.3-live-server-amd64.iso"
          networks:
            - name: VM Network
              device_type: vmxnet3
        delegate_to: localhost
        register: deploy_vm
